CREATE DATABASE bdEscola
USE bdEscola 
Go
CREATE TABLE tbAluno(
	idAluno INT PRIMARY KEY IDENTITY(1,1)
	,nomeAluno VARCHAR(60) NOT NULL
	,dtNascAluno SMALLDATETIME NOT NULL
	,rgAluno VARCHAR (20) NOT NULL
	,naturaAluno VARCHAR (60) NOT NULL
)
CREATE TABLE tbCurso (
	idCurso INT PRIMARY KEY IDENTITY(1,1)
	,nomeCurso VARCHAR (80) NOT NULL
	,cargaHrCurso SMALLDATETIME NOT NULL
	,valorCurso SMALLMONEY NOT NULL
	)

CREATE TABLE tbTurma(
	idTurma INT PRIMARY KEY IDENTITY (1,1)
	,nomeTurma VARCHAR (30) NOT NULL
	,idCurso INT FOREIGN KEY REFERENCES tbCurso (idCurso)
	,hrtURMA SMALLDATETIME NOT NULL
)
CREATE TABLE tbMatricula(
	idMatricula INT PRIMARY KEY IDENTITY(1,1)
	,dtMatricula SMALLDATETIME NOT NULL
	,idAluno INT FOREIGN KEY REFERENCES tbAluno(idAluno)
	,idTurma INT FOREIGN KEY REFERENCES tbTurma (idTurma)
	)


	---DROP DATABASE bdEscola--